### ISSUE TITLE
RuntimeError: the sip module implements API v12.0 to v12.8 but the PyQt5.QtCore module requires API v12.9

### ISSUE THREAD

**Issue by DoubleF3lix** [raccoonML/Real-Time-Voice-Cloning#1]
I was following the steps in the README and everything worked fine until I got to the last step: running it. I got this large error:
```py
(venv) D:\Documents\Coding\Python\Voice Cloner>python demo_toolbox.py
Traceback (most recent call last):
  File "D:\Documents\Coding\Python\Voice Cloner\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "D:\Documents\Coding\Python\Voice Cloner\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "D:\Documents\Coding\Python\Voice Cloner\toolbox\ui.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\pwill\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 2500, in <module>
    switch_backend(rcParams["backend"])
  File "C:\Users\pwill\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\__init__.py", line 621, in __getitem__
    plt.switch_backend(rcsetup._auto_backend_sentinel)
  File "C:\Users\pwill\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 257, in switch_backend
    switch_backend(candidate)
  File "C:\Users\pwill\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 277, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "C:\Users\pwill\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 278, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "C:\Users\pwill\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\pwill\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "C:\Users\pwill\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\backends\backend_qt5.py", line 13, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "C:\Users\pwill\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 11, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File "C:\Users\pwill\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\backends\qt_compat.py", line 174, in <module>
    _setup()
  File "C:\Users\pwill\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\backends\qt_compat.py", line 79, in _setup_pyqt5
    from PyQt5 import QtCore, QtGui, QtWidgets
RuntimeError: the sip module implements API v12.0 to v12.8 but the PyQt5.QtCore module requires API v12.9
```

What did I do wrong? I'm not sure what the `sip` module is, or what the error actually means.

**Comment by raccoonML** [comment]
Please follow my [guide to install Python 3.7.9](https://www.patreon.com/posts/guide-install-in-59934677), and then try the [installation steps](https://github.com/raccoonML/Real-Time-Voice-Cloning/tree/master#readme) again.

Either uninstall Python 3.9 first, or adjust the PATH variables so the 3.7.9 installation takes precedence over 3.9 if you want to keep it. The specific versions of installed packages differ with the Python version so it is best to pick a proven one to minimize these sorts of errors.

**Comment by DoubleF3lix** [comment]
Using 3.7 worked. Thanks.
