### ISSUE TITLE
tensorflow model not found

### ISSUE THREAD

**Issue by Archviz360** [raccoonML/Real-Time-Voice-Cloning#3]
Hi! TensorFlow model is not found. cant install here is the message i got 

error: could not find a version that satisfies the requirement tensorflow==1.15 (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.8.0rc0) error: no matching distribution found for tensorflow==1.15

then it says no module named TensorFlow was found. here is the error i got when i try to run the software 

PS C:\Users\JS\Desktop\Eudora\RTVC-Swedish> python demo_toolbox.py
2022-01-19 21:05:48.201452: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-01-19 21:05:48.202513: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "C:\Users\JS\Desktop\Eudora\RTVC-Swedish\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\JS\Desktop\Eudora\RTVC-Swedish\toolbox\__init__.py", line 3, in <module>
    from synthesizer.inference import Synthesizer
  File "C:\Users\JS\Desktop\Eudora\RTVC-Swedish\synthesizer\inference.py", line 1, in <module>
    from synthesizer.tacotron2 import Tacotron2
  File "C:\Users\JS\Desktop\Eudora\RTVC-Swedish\synthesizer\tacotron2.py", line 3, in <module>
    from synthesizer.models import create_model
  File "C:\Users\JS\Desktop\Eudora\RTVC-Swedish\synthesizer\models\__init__.py", line 1, in <module>
    from .tacotron import Tacotron
  File "C:\Users\JS\Desktop\Eudora\RTVC-Swedish\synthesizer\models\tacotron.py", line 4, in <module>
    from synthesizer.models.helpers import TacoTrainingHelper, TacoTestHelper
  File "C:\Users\JS\Desktop\Eudora\RTVC-Swedish\synthesizer\models\helpers.py", line 3, in <module>
    from tensorflow.contrib.seq2seq import Helper
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by raccoonML** [comment]
Your Python version is too new. Tensorflow 1.15 is only available for Python 3.7 and earlier. Please follow the instructions on the [release page](https://github.com/raccoonML/Real-Time-Voice-Cloning/releases/tag/Swedish-1) and let me know if you have any other issues.
